import { useEffect, useState } from 'react';
import { Menu, X, ArrowUpRight, Search, Download } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import Logo from './Logo';
import ThemeToggle from './ThemeToggle';
const links=[['Work','#work'],['About','#about'],['Stack','#stack'],['Contact','#contact']];
export default function Navbar(){
 const [open,setOpen]=useState(false),[scrolled,setScrolled]=useState(false),[hidden,setHidden]=useState(false),[active,setActive]=useState('#work'); const location=useLocation();const navigate=useNavigate();
 useEffect(()=>{let last=window.scrollY;const on=()=>{const y=window.scrollY;setScrolled(y>24);setHidden(y>last+8&&y>130);if(y<40)setHidden(false);last=y};window.addEventListener('scroll',on,{passive:true});return()=>window.removeEventListener('scroll',on)},[]);
 useEffect(()=>setOpen(false),[location.pathname]);
 useEffect(()=>{if(location.pathname!=='/')return;const obs=new IntersectionObserver(entries=>{const v=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(v)setActive('#'+v.target.id)},{rootMargin:'-30% 0px -55% 0px',threshold:[.1,.25,.5]});links.forEach(([,h])=>{const el=document.querySelector(h);if(el)obs.observe(el)});return()=>obs.disconnect()},[location.pathname]);
 const go=hash=>{setOpen(false);if(location.pathname!=='/'){navigate('/'+hash);return}document.querySelector(hash)?.scrollIntoView({behavior:'smooth',block:'start'});history.replaceState(null,'',hash)};
 return <header className={`nav-wrap ${scrolled?'nav-scrolled':''} ${hidden?'nav-hidden':''}`}><nav className="nav container" aria-label="Primary navigation"><Link to="/" className="nav-logo"><Logo/></Link><div className="nav-links">{links.map(([label,href])=><button key={href} className={active===href?'active':''} data-cursor onClick={()=>go(href)}>{label}</button>)}</div><div className="nav-actions"><button className="nav-search" data-cursor onClick={()=>window.dispatchEvent(new KeyboardEvent('keydown',{key:'k',ctrlKey:true}))}><Search size={15}/><span>Ctrl K</span></button><ThemeToggle/><a className="nav-resume" href="/Pratik_Raj_Resume.pdf" download="Pratik_Raj_Resume.pdf" data-cursor><Download size={14}/> Resume</a><Link className="nav-cta" to="/contact" data-cursor>Let's talk <ArrowUpRight size={14}/></Link><button className="menu-btn" data-cursor onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-label={open?'Close navigation':'Open navigation'}>{open?<X size={21}/>:<Menu size={21}/>}</button></div></nav><AnimatePresence>{open&&<motion.div className="mobile-menu" initial={{opacity:0,y:-12,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-12,scale:.98}} transition={{duration:.22}}><div className="mobile-menu-inner">{links.map(([label,href],i)=><motion.button key={href} data-cursor initial={{opacity:0,x:-12}} animate={{opacity:1,x:0}} transition={{delay:i*.05}} onClick={()=>go(href)}>{label}<span>0{i+1}</span></motion.button>)}<a className="mobile-resume" href="/Pratik_Raj_Resume.pdf" download="Pratik_Raj_Resume.pdf"><Download size={14}/> Download resume</a><Link className="mobile-contact" to="/contact">Let's talk <ArrowUpRight size={17}/></Link></div></motion.div>}</AnimatePresence></header>
}
